spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:6603/file_db
    username: root
    password: 46Fr5gRLAH6wylaqDR32^a8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties.hibernate:
      show_sql: false
      hbm2ddl.auto: validate

